"""
Safe data loading wrapper for the nowcasting app.

Calls the existing fetch functions but handles missing optional files
(NS factors, aligned yields) gracefully — those are generated by the main
VAR pipeline and may not exist yet. FRED/ECB/IPEA data still loads fine.
"""

import sys
from pathlib import Path

import pandas as pd

_APP_DIR = Path(__file__).parent.resolve()
_ALT_DIR = _APP_DIR.parent.resolve()
sys.path.insert(0, str(_ALT_DIR))

from src.data_macro import (
    fetch_fred_bulk,
    fetch_ecb_bulk,
    fetch_ipea_bulk,
    PROJECT_ROOT,
)


def _try_load_csv(path: Path, label: str) -> pd.DataFrame:
    """Load a CSV if it exists; return empty DataFrame with a printed notice if not."""
    if path.exists():
        return pd.read_csv(path, index_col=0, parse_dates=True)
    print(f"  [{label}] not found at {path} — skipping (run the main VAR pipeline to generate it).")
    return pd.DataFrame()


def fetch_all_macro_safe(
    start: str = "2000-01-01",
    end: str = "2026-06-01",
    force: bool = False,
    api_key: str | None = None,
) -> dict:
    """
    Fetch all macro data with graceful fallback for missing optional files.

    Returns the same dict shape as fetch_all_macro():
        fred, ecb, ipea, ns_factors, yields
    Missing files produce empty DataFrames instead of crashing.
    """
    print("=== Fetching FRED ===")
    fred = fetch_fred_bulk(start=start, end=end, force=force, api_key=api_key)

    print("\n=== Fetching ECB ===")
    ecb = fetch_ecb_bulk(start=start, end=end, force=force)

    print("\n=== Fetching IPEA ===")
    ipea = fetch_ipea_bulk(force=force)

    print("\n=== Loading NS factors (optional) ===")
    ns = _try_load_csv(
        PROJECT_ROOT / "data" / "factors" / "ns_factors_5c.csv",
        "NS factors",
    )

    print("\n=== Loading yields (optional) ===")
    yields = _try_load_csv(
        PROJECT_ROOT / "data" / "raw" / "aligned_yields_5c.csv",
        "Aligned yields",
    )

    return {
        "fred":       fred,
        "ecb":        ecb,
        "ipea":       ipea,
        "ns_factors": ns,
        "yields":     yields,
    }
